name: Generic Cosmos FA Dev workflow
on:
    push:
      branches: [ dev ]
jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Set-up Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          cache: true
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity minimal